variables:
  IMAGE_TAGGED_NAME: "portfolio-app:latest"
  # Docker configuration for socket connection
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:latest
  before_script:
    # download docker file from docker-configs repo
    - wget -O /opt/Dockerfile --header "PRIVATE-TOKEN:${GITLAB_READ_TOKEN}" http://172.30.0.2:8929/projects/2/repository/files/dockerfiles%2Fportfolio%2Fportfolio.cloud.Dockerfile/raw\?ref=master
    - docker --version
    - echo "=== Contenu du Dockerfile téléchargé ==="
    - head -20 /opt/Dockerfile
    - echo "=== Fin du contenu ==="
    - docker --version
    - docker info 
    - docker info  # Verify Docker connection
  script:
    - docker build -f /opt/Dockerfile -t "${IMAGE_TAGGED_NAME}" --no-cache --network=host .
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_ID == "1"

deploy-job:
  stage: deploy
  image: docker/compose:latest
  needs: [build-job]
  before_script:
    # download docker-compose file from docker-configs repo
    - wget -O /opt/docker-compose.yml --header "PRIVATE-TOKEN:${GITLAB_READ_TOKEN}" http://172.30.0.2:8929/projects/2/repository/files/docker-compose%2Fportfolio%2Fdocker-compose.yml/raw\?ref=master
    - docker --version
    - docker info  # Verify Docker connection
  script:
    - docker compose -f /opt/docker-compose.yml down || true
    - docker compose -f /opt/docker-compose.yml up -d --build
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_ID == "1"