variables:
  IMAGE_TAGGED_NAME: "portfolio-app:latest"
  CI_SERVER_URL: http://host.docker.internal:8929

stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker
  before_script:
    # download docker file from docker-configs repo
    - wget -O /opt/Dockerfile --header "PRIVATE-TOKEN:${GITLAB_READ_TOKEN}" http://gitlab:8929/cedrik/projects/2/repository/files/dockerfiles%2Fportfolio%2Fportfolio.cloud.Dockerfile/raw\?ref=master
    - docker --version
  script:
    - docker build -f /opt/Dockerfile -t "${IMAGE_TAGGED_NAME}" --no-cache --network=host .
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_ID == "1"

deploy-job:
  stage: deploy
  image: docker/compose:latest
  needs: [build-job]
  before_script:
    # download docker-compose file from docker-configs repo
    - wget -O /opt/docker-compose.yml --header "PRIVATE-TOKEN:${GITLAB_READ_TOKEN}" http://gitlab:8929/cedrik/projects/2/repository/files/docker-compose%2Fportfolio%2Fdocker-compose.yml/raw\?ref=master
  script:
    - docker compose -f /opt/docker-compose.yml down || true
    - docker compose -f /opt/docker-compose.yml up -d --build
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_ID == "1"